version: "3.9"

services:
  api:
    build: .
    container_name: api_nodejs
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_nodejs
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data:
